#!/usr/bin/env bash
# Installs nginx server
sudo apt-get -y update
sudo apt-get -y install nginx

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

string_for_replacement="server_name _;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/ext\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
